# All instances of ci-cd branch will be changed once .travis.yml
# is confirmed to have correct settings

language: node_js
node_js:
- stable
cache:
  directories:
    - client/node_modules
    - server/node_modules
env:
  - DIR=client
  - DIR=server
script: 'true'
branches:
  only:
  - ci-cd
before_install: cd $DIR
install: npm install
script: npm test