# All instances of ci-cd branch will be changed once .travis.yml
# is confirmed to have correct settings

language: node_js
node_js:
- stable

branches:
  only:
  - ci-cd
jobs:
  include:
    - stage: install fronend dependencies
      before_install: cd client
      install: npm install
    - stage: install backend dependencies
      before_install: cd ../server
      install: npm install
    - stage: frontend unit tests
      script: cd client
      script: npm test
    - stage: backend unit tests
      script: cd ../server
      script: npm test