# All instances of ci-cd branch will be changed once .travis.yml
# is confirmed to have correct settings

language: node_js
node_js:
- stable
cache:
  directories:
    - client/node_modules
    - server/node_modules
script: 'true'
branches:
  only:
  - ci-cd
jobs:
  include:
    - stage: Frontend Unit Tests
      before_install: cd client
      install: npm install
      script: npm test
    - stage: Backend Unit Tests
      before_install: cd server
      install: npm install
      script: npm test