language: node_js
node_js:
- stable
cache:
  directories:
    - client/node_modules
    - server/node_modules
env:
  - DIR=client
  - DIR=server
script: 'true'
branches:
  only:
  - master
  - dev
before_install: cd $DIR
install: npm install
script: npm test